site_name: New York City Yellow Trip Stream Processing
site_url: https://lnynhi02.github.io/stream-processing-pipeline-docs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Documentation: index.md
  - Changelog: changelog.md
  - Deployment: deployment.md
  - GitHub Repository: https://github.com/lnynhi02/Stream-Processing-Pipeline
  - References: references.md

theme:
  name: material

  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True